// lib/theme/design_tokens.dart
// Design Tokens Template for Flutter Apps
//
// This file serves as a single source of truth for all visual design values.
// Update this file to change the visual appearance across the entire app.
//
// Generated by: UI Styling & Visual Polish Skill
// Date: [Date]
// Visual Identity: [Brief description, e.g., "Warm, organized, trustworthy"]

import 'package:flutter/material.dart';

/// Central design tokens for consistent visual styling throughout the app.
///
/// This class contains all color, typography, spacing, and component styling
/// values used in the app. Use these constants instead of hardcoded values
/// to ensure visual consistency and easy theme updates.
///
/// Usage:
/// ```dart
/// // Use in widgets
/// Container(
///   color: DesignTokens.primaryColor,
///   padding: EdgeInsets.all(DesignTokens.spacingMd),
///   child: Text(
///     'Hello',
///     style: TextStyle(fontSize: DesignTokens.bodySize),
///   ),
/// )
///
/// // Use in theme configuration
/// ThemeData(
///   colorScheme: ColorScheme.light(
///     primary: DesignTokens.primaryColor,
///   ),
/// )
/// ```
class DesignTokens {
  // Private constructor to prevent instantiation
  DesignTokens._();

  // ==========================================================================
  // COLOR SYSTEM
  // ==========================================================================

  // --------------------------------------------------------------------------
  // Primary Colors (Brand Identity)
  // --------------------------------------------------------------------------
  /// Main brand color, used for key actions and primary UI elements
  static const Color primaryColor = Color(0xFF2196F3); // TODO: Replace with your primary color

  /// Darker variant of primary color, used for pressed states and emphasis
  static const Color primaryDark = Color(0xFF1976D2);

  /// Lighter variant of primary color, used for hover states and tints
  static const Color primaryLight = Color(0xFF42A5F5);

  // --------------------------------------------------------------------------
  // Secondary/Accent Colors
  // --------------------------------------------------------------------------
  /// Accent color for calls-to-action and highlights
  static const Color accentColor = Color(0xFF4CAF50); // TODO: Replace with your accent color

  /// Darker accent variant
  static const Color accentDark = Color(0xFF388E3C);

  /// Lighter accent variant
  static const Color accentLight = Color(0xFF66BB6A);

  // --------------------------------------------------------------------------
  // Neutral Palette
  // --------------------------------------------------------------------------
  /// Main background color for screens
  static const Color backgroundColor = Color(0xFFF5F5F5);

  /// Surface color for cards and elevated elements
  static const Color surfaceColor = Color(0xFFFFFFFF);

  /// Border and divider color
  static const Color borderColor = Color(0xFFE0E0E0);

  /// Disabled element color
  static const Color disabledColor = Color(0xFFBDBDBD);

  // --------------------------------------------------------------------------
  // Text Colors
  // --------------------------------------------------------------------------
  /// Primary text color for main content
  static const Color textPrimary = Color(0xFF212121);

  /// Secondary text color for supporting content
  static const Color textSecondary = Color(0xFF757575);

  /// Disabled text color
  static const Color textDisabled = Color(0xFFBDBDBD);

  /// Text color on primary colored backgrounds
  static const Color textOnPrimary = Color(0xFFFFFFFF);

  // --------------------------------------------------------------------------
  // Semantic Colors
  // --------------------------------------------------------------------------
  /// Success color for positive actions and confirmations
  static const Color successColor = Color(0xFF4CAF50);

  /// Warning color for cautions and important notices
  static const Color warningColor = Color(0xFFFFC107);

  /// Error color for errors and destructive actions
  static const Color errorColor = Color(0xFFF44336);

  /// Info color for informational messages
  static const Color infoColor = Color(0xFF2196F3);

  // ==========================================================================
  // TYPOGRAPHY SYSTEM
  // ==========================================================================

  // --------------------------------------------------------------------------
  // Font Family
  // --------------------------------------------------------------------------
  /// Primary font family (defaults to system font)
  static const String fontFamily = ''; // Empty string uses system default

  // --------------------------------------------------------------------------
  // Font Sizes (in sp - scalable pixels)
  // --------------------------------------------------------------------------
  /// Display text size - for hero sections
  static const double displaySize = 32.0;

  /// Heading 1 size - for screen titles
  static const double heading1Size = 24.0;

  /// Heading 2 size - for section headings
  static const double heading2Size = 20.0;

  /// Heading 3 size - for subsection headings
  static const double heading3Size = 18.0;

  /// Large body text size - for emphasized content
  static const double bodyLargeSize = 16.0;

  /// Standard body text size - for main content
  static const double bodySize = 14.0;

  /// Small body text size - for supporting text
  static const double bodySmallSize = 12.0;

  /// Caption text size - for labels and fine print
  static const double captionSize = 11.0;

  // --------------------------------------------------------------------------
  // Font Weights
  // --------------------------------------------------------------------------
  /// Regular weight for body text
  static const FontWeight weightRegular = FontWeight.w400;

  /// Medium weight for emphasis and buttons
  static const FontWeight weightMedium = FontWeight.w500;

  /// Semibold weight for headings
  static const FontWeight weightSemibold = FontWeight.w600;

  /// Bold weight for strong emphasis (use sparingly)
  static const FontWeight weightBold = FontWeight.w700;

  // --------------------------------------------------------------------------
  // Line Heights (unitless multipliers)
  // --------------------------------------------------------------------------
  /// Tight line height for headings
  static const double tightLineHeight = 1.2;

  /// Normal line height for body text
  static const double normalLineHeight = 1.5;

  /// Relaxed line height for long-form content
  static const double relaxedLineHeight = 1.8;

  // ==========================================================================
  // SPACING SYSTEM
  // ==========================================================================

  // --------------------------------------------------------------------------
  // Base Unit: Choose 4px or 8px as your base
  // All spacing values should be multiples of the base unit
  // --------------------------------------------------------------------------
  static const double baseUnit = 8.0; // TODO: Choose 4.0 or 8.0

  // --------------------------------------------------------------------------
  // Spacing Scale
  // --------------------------------------------------------------------------
  /// Extra extra small spacing (tight spaces, icon padding)
  static const double spacingXXs = baseUnit * 0.25; // 2px if base is 8px

  /// Extra small spacing (very compact)
  static const double spacingXs = baseUnit * 0.5; // 4px if base is 8px

  /// Small spacing (compact gaps between related elements)
  static const double spacingSm = baseUnit * 1; // 8px if base is 8px

  /// Medium spacing (standard gap between elements)
  static const double spacingMd = baseUnit * 2; // 16px if base is 8px

  /// Large spacing (section separators)
  static const double spacingLg = baseUnit * 3; // 24px if base is 8px

  /// Extra large spacing (major section breaks)
  static const double spacingXl = baseUnit * 4; // 32px if base is 8px

  /// Extra extra large spacing (large screen padding)
  static const double spacingXXl = baseUnit * 6; // 48px if base is 8px

  // --------------------------------------------------------------------------
  // Component Padding Standards
  // --------------------------------------------------------------------------
  /// Standard button padding (vertical, horizontal)
  static const EdgeInsets buttonPadding = EdgeInsets.symmetric(
    vertical: spacingSm,
    horizontal: spacingMd,
  );

  /// Standard card padding
  static const EdgeInsets cardPadding = EdgeInsets.all(spacingMd);

  /// Standard list item padding
  static const EdgeInsets listItemPadding = EdgeInsets.symmetric(
    vertical: spacingSm,
    horizontal: spacingMd,
  );

  /// Standard input field padding
  static const EdgeInsets inputPadding = EdgeInsets.all(spacingMd);

  /// Standard screen horizontal padding
  static const EdgeInsets screenPadding = EdgeInsets.symmetric(
    horizontal: spacingMd,
  );

  // ==========================================================================
  // COMPONENT STYLING
  // ==========================================================================

  // --------------------------------------------------------------------------
  // Border Radius
  // --------------------------------------------------------------------------
  /// Small border radius for buttons, chips
  static const double borderRadiusSmall = 8.0;

  /// Medium border radius for cards, inputs
  static const double borderRadiusMedium = 12.0;

  /// Large border radius for dialogs, large cards
  static const double borderRadiusLarge = 16.0;

  /// Circular border radius for avatars, icon buttons
  static const double borderRadiusCircular = 999.0;

  // --------------------------------------------------------------------------
  // Elevation/Shadow Levels
  // --------------------------------------------------------------------------
  /// No elevation - flat elements
  static const double elevation0 = 0.0;

  /// Level 1 elevation for cards
  static const double elevation1 = 2.0;

  /// Level 2 elevation for floating action buttons
  static const double elevation2 = 4.0;

  /// Level 3 elevation for dialogs and menus
  static const double elevation3 = 8.0;

  /// Level 4 elevation for navigation drawer
  static const double elevation4 = 16.0;

  // --------------------------------------------------------------------------
  // Custom Shadow Definitions (if not using Material elevation)
  // --------------------------------------------------------------------------
  /// Subtle shadow for cards
  static final List<BoxShadow> shadowLevel1 = [
    BoxShadow(
      color: Colors.black.withOpacity(0.08),
      blurRadius: 4,
      offset: const Offset(0, 2),
    ),
  ];

  /// Medium shadow for floating elements
  static final List<BoxShadow> shadowLevel2 = [
    BoxShadow(
      color: Colors.black.withOpacity(0.12),
      blurRadius: 8,
      offset: const Offset(0, 4),
    ),
  ];

  /// Strong shadow for dialogs
  static final List<BoxShadow> shadowLevel3 = [
    BoxShadow(
      color: Colors.black.withOpacity(0.16),
      blurRadius: 16,
      offset: const Offset(0, 8),
    ),
  ];

  // --------------------------------------------------------------------------
  // Border Widths
  // --------------------------------------------------------------------------
  /// Hairline border for subtle dividers
  static const double borderWidthHairline = 1.0;

  /// Thin border for standard borders and focus states
  static const double borderWidthThin = 2.0;

  /// Medium border for emphasized borders
  static const double borderWidthMedium = 3.0;

  // --------------------------------------------------------------------------
  // Icon Sizing
  // --------------------------------------------------------------------------
  /// Small icon size for inline icons
  static const double iconSizeSmall = 16.0;

  /// Standard icon size for UI icons
  static const double iconSizeMedium = 24.0;

  /// Large icon size for feature icons and empty states
  static const double iconSizeLarge = 32.0;

  /// Extra large icon size for hero icons
  static const double iconSizeXLarge = 48.0;

  // --------------------------------------------------------------------------
  // Touch Target Sizes (minimum 44px for accessibility)
  // --------------------------------------------------------------------------
  /// Minimum touch target size (Material Design guideline)
  static const double minTouchTarget = 44.0;

  /// Standard touch target size
  static const double touchTargetStandard = 48.0;

  // ==========================================================================
  // ANIMATION & TIMING
  // ==========================================================================

  // --------------------------------------------------------------------------
  // Animation Durations (in milliseconds)
  // --------------------------------------------------------------------------
  /// Fast animation duration for micro-interactions
  static const Duration animationFast = Duration(milliseconds: 150);

  /// Standard animation duration for most transitions
  static const Duration animationStandard = Duration(milliseconds: 300);

  /// Slow animation duration for complex animations
  static const Duration animationSlow = Duration(milliseconds: 500);

  // --------------------------------------------------------------------------
  // Animation Curves
  // --------------------------------------------------------------------------
  /// Standard easing curve for most animations
  static const Curve animationCurveStandard = Curves.easeInOut;

  /// Emphasized easing for attention-grabbing animations
  static const Curve animationCurveEmphasized = Curves.easeOutCubic;

  // ==========================================================================
  // BREAKPOINTS (for responsive design)
  // ==========================================================================

  /// Small phone breakpoint
  static const double breakpointSmall = 320.0;

  /// Standard phone breakpoint
  static const double breakpointMedium = 375.0;

  /// Large phone breakpoint
  static const double breakpointLarge = 414.0;

  /// Tablet breakpoint
  static const double breakpointTablet = 768.0;

  /// Desktop breakpoint
  static const double breakpointDesktop = 1024.0;

  // ==========================================================================
  // HELPER METHODS
  // ==========================================================================

  /// Returns appropriate spacing based on device size
  static double responsiveSpacing(BuildContext context, {
    double small = spacingSm,
    double medium = spacingMd,
    double large = spacingLg,
  }) {
    final width = MediaQuery.of(context).size.width;
    if (width < breakpointMedium) return small;
    if (width < breakpointLarge) return medium;
    return large;
  }

  /// Returns whether the screen is considered small
  static bool isSmallScreen(BuildContext context) {
    return MediaQuery.of(context).size.width < breakpointMedium;
  }

  /// Returns whether the screen is considered large
  static bool isLargeScreen(BuildContext context) {
    return MediaQuery.of(context).size.width >= breakpointTablet;
  }
}

// =============================================================================
// USAGE EXAMPLES
// =============================================================================

// Example 1: Using colors
// Container(color: DesignTokens.primaryColor)

// Example 2: Using typography
// Text('Hello', style: TextStyle(
//   fontSize: DesignTokens.bodySize,
//   fontWeight: DesignTokens.weightMedium,
// ))

// Example 3: Using spacing
// Padding(
//   padding: EdgeInsets.all(DesignTokens.spacingMd),
//   child: child,
// )

// Example 4: Using component styling
// Container(
//   decoration: BoxDecoration(
//     borderRadius: BorderRadius.circular(DesignTokens.borderRadiusMedium),
//     boxShadow: DesignTokens.shadowLevel1,
//   ),
// )

// Example 5: Responsive spacing
// Padding(
//   padding: EdgeInsets.all(
//     DesignTokens.responsiveSpacing(context),
//   ),
// )
